### ISSUE TITLE
Update README Pre-reqs section with minimal disk requirements

### ISSUE THREAD

**Issue by osowski** [Seagate/cortx-k8s#116]
Update https://github.com/Seagate/cortx-k8s/tree/main#cortx-on-kubernetes-prerequisites section to include the minimal disk requirements for deploying CORTX on Kubernetes:

- requiring a mounted disk for the path to the value defined in solution.yaml via the "storage_provisioner_path". This can be the local root volume as well, but if using the `prereq-deploy-cortx-cloud.sh` script, it expects an entire disk that it can use.
- requiring at least two volumes for a single CVG per each node - 1 for metadata and at least 1 for data
  - this should be resolved or determined if this needs to be the entire block device (eg /dev/sdg) or if this can be a volume on the device (eg /dev/sdg1 , /dev/sdg2 etc).

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-29016. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by hessio** [comment]
Hi @osowski - just want to check what the status of this issue is

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
