### ISSUE TITLE
README has incorrect URL to AWS QSG

### ISSUE THREAD

**Issue by osowski** [Seagate/cortx-k8s#121]
README.md currently points to https://github.com/Seagate/cortx-k8s/blob/UDX-6683_move_documentation_to_readme_md/doc/cortx-aws-k8s-installation.md

It should point to https://github.com/Seagate/cortx-k8s/blob/main/doc/cortx-aws-k8s-installation.md instead

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-29102. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Richard Osowski commented in Jira Server:

Fixed URL typo

**Comment by cortx-admin** [comment]
> Richard Osowski commented in Jira Server:

Fixed URL typo.

**Comment by cortx-admin** [comment]
> Richard Osowski commented in Jira Server:

Fixed URL typo
