### ISSUE TITLE
Convert confluence doc into markdown

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-k8s#123]
At this location (https://github.com/Seagate/cortx-k8s#using-cortx-on-kubernetes), there is a TODO item which looks like:

Using CORTX on Kubernetes
TODO Port https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/754155622/CORTX+Kubernetes+N-Pod+Deployment+and+Upgrade+Document+using+Services+Framework#5.-Understanding-Management-and-S3-Endpoints-and-configuring-External-Load-balancer-service(Optional) here or into a linked doc/readme file. 

This action needs to be done and the PR doing it needs to refer back to this Issue.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-29123. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by anubhav06** [comment]
Hi! Can I work on this ?

**Comment by johnbent** [comment]
Hello @anubhav06 , yes, that would be awesome! Please let us know if you have any questions. Thanks!

**Comment by anubhav06** [comment]
The PR has to be raised against which branch ?

**Comment by anubhav06** [comment]
Just a clarification, do we have to convert just the 5th point into markdown (as the link refers to the 5th point of the docs) or the entire web page ?

**Comment by johnbent** [comment]
> The PR has to be raised against which branch ?

integration please

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
