### ISSUE TITLE
Deployment Guide Needed for GCP

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-k8s#134]
We currently have a guide for deployment in AWS: https://github.com/Seagate/cortx-k8s/blob/integration/doc/cortx-aws-k8s-installation.md

It would be good to have a comparable deployment guide for GCP.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-29169. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
