### ISSUE TITLE
CSM API call returns 404

### ISSUE THREAD

**Issue by trshaffer** [Seagate/cortx-k8s#140]
I was trying out the new v0.1.0 release with the AWS QSG (and CloudFormation for #119), and the deployment steps went smoothly.
In [section 4.1](https://github.com/Seagate/cortx-k8s/blob/integration/doc/cortx-aws-k8s-installation.md#41-use-cortx-csm-management-api-to-provision-an-s3-account), however, I can't get the CSM calls to work. The `login` works as expected and gives me a bearer token, but the call to `s3_accounts` just returns 404.

Did something with CSM change since the last release, or am I missing something simple?

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-29201. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by keithpine** [comment]
0.1.0 is based on RGW, so the entire S3 account model has changed.

**Comment by johnbent** [comment]
Thanks @keithpine .  Will the regression tests added recently by @walterlopatka help find things like this in the future? It seems like we need to update that QSG. I wonder if this also breaks the recent minikube QSG that was added.

**Comment by keithpine** [comment]
I'm sure eventually some regression test would surface things like this (I would sure hope so). My understanding about users is very limited (the only information I've found is private in Confluence). As of now, an admin user is created by the deployment and that user can be used for S3 IO.

The Access Key for the default admin user is specified by `solution.common.s3.auth_admin` (default `sgiamadmin`) and the Secret Key is specified by `solution.secrets.content.s3_auth_admin_secret`.

Note that the example guides are not impacted because they specifically reference a release version, e.g. v0.0.22, which does not use RGW. We will want to update those guides, for sure.

**Comment by walterlopatka** [comment]
@trshaffer @johnbent , I noticed the same thing while doing my own work,  I will ask the development team for information on this and will post the results here.

Regarding regression test, I do intend to integrate into it basic CSM API call and S3 I/O.  I can't guarantee when that will be (but I would love to see it by the end of March.

**Comment by walterlopatka** [comment]
@trshaffer , the API has changed.   There is no longer an "s3_accounts" API because RGW does not have an s3_account concept, but only has IAM users.

Instead of using "s3_accounts", use `api/v2/s3/iam/users`.

[This page in Confluence describes the RGW-based API.](https://seagate-systems.atlassian.net/l/c/XZ2rWE7U)

(I'm not sure why this is in the Private space.)

(The problem I was having earlier is that I was using the incorrect username password.  But since you were able to get the token, I can see this wasn't your problem.)

**Comment by johnbent** [comment]
@walterlopatka , good catch. They shouldn't have been in private. I moved them to public:
https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/884703300/Create+IAM+user+REST+API+Specifications

By the way, the old private link you pasted automatically forwards. That's cool!

**Comment by osowski** [comment]
@trshaffer Have you had a chance to look if this issue persist using the new RGW-based IAM commands?

**Comment by keithpine** [comment]
I was able to create a new IAM user with linked API, and could use S3 IO with that user.

**Comment by trshaffer** [comment]
I'll close this then, since the instructions are working as written. Just need to ensure the guide gets updated with the next version bump :)

**Comment by cortx-admin** [comment]
> Walter Lopatka commented in Jira Server:

NA

**Comment by cortx-admin** [comment]
> Walter Lopatka commented in Jira Server:

Resolved in GitHub.  (Issue was user misunderstanding of a recent interface change.)

**Comment by cortx-admin** [comment]
> Walter Lopatka commented in Jira Server:

Closed in GitHub
