### ISSUE TITLE
Update AWS deployment guide and CloudFormation templates

### ISSUE THREAD

**Issue by keithpine** [Seagate/cortx-k8s#201]
### Problem

Release v0.3.0 introduced some changes that affects the current AWS deployment guide. Here are some known cases:

1. Some solution.yaml keys are no longer required
2. References to solution.yaml should be changed to solution.example.yaml

There may be other changes needed, such as interaction with CSM and IAM usage. The guide and templates refer to v0.0.22. It is likely out of date after the switch to RGW S3 (v0.1.0). The guide and templates should be audited and updated as needed.

### Expected behavior

- Don't configure `solution.common.setup_size` solution.yaml setting
- Don't configure `solution.images.openldap` solution.yaml setting
- Replace usage of `solution.yaml` with `solution.example.yaml`
- Update usage of `prereq-deploy-cortx-cloud.sh` script (script args changed)
- etc...

### How to reproduce

N/A

### CORTX on Kubernetes version

v0.3.0

### Deployment information

AWS CloudFormation

### Additional information

Related to:

- PR #183 (CORTX-29720)
- Issue #173

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-30639. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
