### ISSUE TITLE
More PR checks needed

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-k8s#50]
Here is the PR check section for this repo:
![image](https://user-images.githubusercontent.com/2047294/149398800-73c63aa1-f64c-4c90-8996-3193f7ca8b71.png)

It should be uniform with the rest of our repos and have many more checks in place like this:
![image](https://user-images.githubusercontent.com/2047294/149398902-53fd2ccc-4794-454e-8d23-098ece1ddc43.png)

I will create a Jira ticket and ask Amol's team to do the needful.

**Comment by johnbent** [comment]
https://jts.seagate.com/browse/EOS-27544 created to track this and ensure it is done.

**Comment by venkuppu-chn** [comment]
Hi @johnbent , 

We have already created the PR for Alex workflow, this needs to be merged. 
https://github.com/Seagate/cortx-k8s/pull/3

CC: @mukul-seagate11

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-27622. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by osowski** [comment]
As mentioned in the individual PRs, we need a universal change across all CORTX repos to fork third-party GitHub Actions and reference the forked versions instead of using third-party repository-hosted actions directly.

Referenced PRs:
- https://github.com/Seagate/cortx-k8s/pull/56
- https://github.com/Seagate/cortx-k8s/pull/41
- https://github.com/Seagate/cortx-k8s/pull/3

**Comment by osowski** [comment]
These have all been merged in with updated locally forked GitHub Actions.

**Comment by cortx-admin** [comment]
> Richard Osowski commented in Jira Server:

Implemented PR checks on GitHub repo

**Comment by cortx-admin** [comment]
> Richard Osowski commented in Jira Server:

Implemented PR checks on GitHub repo

**Comment by cortx-admin** [comment]
> Richard Osowski commented in Jira Server:

Implemented PR checks on GitHub repo
