### ISSUE TITLE
Unable to access the Jenkins job mentioned in the document 

### ISSUE THREAD

**Issue by alfhad** [Seagate/cortx-k8s#59]
While trying to follow [CORTX Kubernetes N-Pod Deployment and Upgrade Document (using Services Framework)](https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/754155622/CORTX+Kubernetes+N-Pod+Deployment+and+Upgrade+Document+using+Services+Framework) I encountered a unreachable link.

Unable to form Kubernetes cluster as the below is inaccessible 

http://eos-jenkins.mero.colo.seagate.com/job/Cortx-kubernetes/job/setup-kubernetes-cluster/

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-27985. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> John Bent commented in Jira Server:

easy community ticket; closing

**Comment by cortx-admin** [comment]
> John Bent commented in Jira Server:

closed

**Comment by cortx-admin** [comment]
> John Bent commented in Jira Server:

closed
