### ISSUE TITLE
Add "Contribution" section to root README

### ISSUE THREAD

**Issue by osowski** [Seagate/cortx-k8s#67]
We need to update the root README.md to include a "Contribution" section detailing the expectations on PRs and project coordination, taking guidance from existing CORTX repositories as available.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-28449. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Richard Osowski commented in Jira Server:

Added CONTRIBUTING.md to the cortx-k8s repo.

**Comment by osowski** [comment]
Resolved via https://github.com/Seagate/cortx-k8s/pull/96

**Comment by cortx-admin** [comment]
> Richard Osowski commented in Jira Server:

Resolved via GitHub

**Comment by cortx-admin** [comment]
> Richard Osowski commented in Jira Server:

Fixed and verified.
