### ISSUE TITLE
Complete "Solution YAML Overview" details on root README

### ISSUE THREAD

**Issue by osowski** [Seagate/cortx-k8s#69]
As we are able to accommodate the solution.yaml changes in our current development cycle, we need to complete the https://github.com/Seagate/cortx-k8s/tree/integration#solution-yaml-overview table for a comprehensive documentation of the solution.yaml format and structure.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-28451. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by walterlopatka** [comment]
@osowski , there has been quite a bit of progress on this since this was submitted.  Maybe not 100% perfect, but really pretty good, and I think it meets the spirit of this issue.  What do you think?

**Comment by osowski** [comment]
Yep, I'm good with where we are currently on that section of the README and its affinity to the underlying Helm Chart values.yaml documentation.

**Comment by cortx-admin** [comment]
> Walter Lopatka commented in Jira Server:

Completed in GitHub

**Comment by cortx-admin** [comment]
> Walter Lopatka commented in Jira Server:

Closed in GitHub

**Comment by cortx-admin** [comment]
> Walter Lopatka commented in Jira Server:

Closed in GitHub
